# Build stage
FROM maven:3.9.8-eclipse-temurin-21 AS dependencies
WORKDIR /app
COPY pom.xml pom.xml
COPY map/pom.xml map/pom.xml
COPY gateway/pom.xml gateway/pom.xml
COPY reduce/pom.xml reduce/pom.xml
RUN mvn -B -e org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline -DexcludeArtifactIds=domain

FROM maven:3.9.8-eclipse-temurin-21 AS builder
WORKDIR /app
COPY --from=dependencies /root/.m2 /root/.m2
COPY --from=dependencies /app /app
COPY map/src /app/map/src
WORKDIR /app/map
RUN mvn -B -e clean install -DskipTests


FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/map/target/*.jar /app.jar
EXPOSE 8080
CMD ["java", "-jar", "/app.jar"]
